title       = "biostudies"
baseURL     = "https://biostudies-cli.tamnd.com/"
description = "A command line for biostudies."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/biostudies-cli"
